### ISSUE TITLE
Fetching in the store constructor

### ISSUE THREAD

**Issue by vladkampov** [madelGeek/crewFlow#3]
https://github.com/madelGeek/crewFlow/blob/master/app/stores/crew.store.ts#L13

Could you please describe why you choose store constructor to be responsible for fetching the data?

**Comment by vladkampov** [comment]
And I'm wondering why you have wrote `return undefined` here. https://github.com/madelGeek/crewFlow/blob/master/app/stores/crew.store.ts#L21

**Comment by madelGeek** [comment]
1. Added to TODO: Move working with server to the api store;
It should be in separate class, for example class crewAPI. Leave it in crew.store.ts for quickness 
2. My bad, it be better to:
```
 const src = 'https://randomuser.me/api/?nat=gb&results=5';
 const dataPromise = loadData(src);
    dataPromise.catch(() => {
      console.warn('Receive data error');
    });
```

**Comment by vladkampov** [comment]
Thanks for your answers
